version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/secbrain"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
