"""Insights reporter - generates reports in various formats."""

from __future__ import annotations

import csv
import json
from datetime import datetime
from pathlib import Path

from secbrain.insights.analyzer import AnalysisResults


class InsightsReporter:
    """Generates reports from analysis results."""

    def __init__(self, output_dir: str | Path = "."):
        """
        Initialize reporter.

        Args:
            output_dir: Directory for output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_markdown(self, results: AnalysisResults, title: str = "SecBrain Insights Report") -> str:
        """
        Generate Markdown report.

        Args:
            results: Analysis results
            title: Report title

        Returns:
            Markdown formatted report
        """
        lines = []
        lines.append(f"# {title}\n")
        lines.append(f"*Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}*\n")

        # Executive Summary
        lines.append("## Executive Summary\n")
        lines.append(f"**Status:** {results.summary.get('status', 'unknown').replace('_', ' ').title()}\n")
        lines.append(f"**Total Insights:** {results.summary.get('total_insights', 0)}\n")
        lines.append(f"**Critical Issues:** {results.summary.get('critical_count', 0)}\n")
        lines.append(f"**High Priority:** {results.summary.get('high_count', 0)}\n")
        lines.append(f"\n**Next Action:** {results.summary.get('next_action', 'N/A')}\n")

        # Key Metrics
        lines.append("\n## Key Metrics\n")
        for key, value in results.metrics.items():
            formatted_key = key.replace('_', ' ').title()
            if isinstance(value, float):
                lines.append(f"- **{formatted_key}:** {value:.2f}\n")
            else:
                lines.append(f"- **{formatted_key}:** {value}\n")

        # Priority Insights
        critical = results.get_critical_insights()
        if critical:
            lines.append("\n## 🔴 Critical Issues\n")
            for insight in critical:
                lines.append(f"\n### {insight.title}\n")
                lines.append(f"{insight.description}\n")
                lines.append(f"\n**Action Required:** {insight.action}\n")

        high = results.get_high_priority_insights()
        if high:
            lines.append("\n## 🟠 High Priority Items\n")
            for insight in high:
                lines.append(f"\n### {insight.title}\n")
                lines.append(f"{insight.description}\n")
                lines.append(f"\n**Recommended Action:** {insight.action}\n")

        # Insights by Category
        lines.append("\n## Insights by Category\n")
        categories = {i.category for i in results.insights}
        for category in sorted(categories):
            cat_insights = results.get_by_category(category)
            if cat_insights:
                lines.append(f"\n### {category.replace('_', ' ').title()}\n")
                for insight in cat_insights:
                    priority_emoji = {
                        "critical": "🔴",
                        "high": "🟠",
                        "medium": "🟡",
                        "low": "⚪",
                    }.get(insight.priority, "⚪")
                    lines.append(f"- {priority_emoji} **{insight.title}** - {insight.description}\n")

        # Recommendations
        if results.recommendations:
            lines.append("\n## Top Recommendations\n")
            for i, rec in enumerate(results.recommendations, 1):
                lines.append(f"{i}. {rec}\n")

        # Footer
        lines.append("\n---\n")
        lines.append("*Generated by SecBrain Insights*\n")

        return "".join(lines)

    def generate_html(self, results: AnalysisResults, title: str = "SecBrain Insights Report") -> str:
        """
        Generate HTML report.

        Args:
            results: Analysis results
            title: Report title

        Returns:
            HTML formatted report
        """
        critical = results.get_critical_insights()
        high = results.get_high_priority_insights()

        status_color = {
            "requires_attention": "#dc3545",
            "review_recommended": "#ffc107",
            "healthy": "#28a745",
        }.get(results.summary.get("status", "unknown"), "#6c757d")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #333;
            border-bottom: 3px solid #007bff;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #555;
            margin-top: 30px;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 5px;
        }}
        .summary {{
            background: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin: 20px 0;
        }}
        .summary-item {{
            display: inline-block;
            margin: 10px 20px 10px 0;
        }}
        .summary-item strong {{
            color: #666;
        }}
        .status {{
            display: inline-block;
            padding: 5px 15px;
            border-radius: 20px;
            background: {status_color};
            color: white;
            font-weight: bold;
        }}
        .insight {{
            background: #fff;
            border-left: 4px solid #ddd;
            padding: 15px;
            margin: 15px 0;
            border-radius: 4px;
        }}
        .insight.critical {{
            border-left-color: #dc3545;
            background: #fff5f5;
        }}
        .insight.high {{
            border-left-color: #ffc107;
            background: #fffef5;
        }}
        .insight.medium {{
            border-left-color: #17a2b8;
            background: #f5fcff;
        }}
        .insight h3 {{
            margin-top: 0;
            color: #333;
        }}
        .action {{
            background: #e7f3ff;
            padding: 10px;
            border-radius: 4px;
            margin-top: 10px;
        }}
        .metrics {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .metric {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
        }}
        .metric-value {{
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
        }}
        .metric-label {{
            color: #666;
            font-size: 14px;
            margin-top: 5px;
        }}
        .recommendations {{
            background: #fff3cd;
            padding: 20px;
            border-radius: 5px;
            border: 1px solid #ffc107;
        }}
        .recommendations ol {{
            margin: 10px 0;
            padding-left: 20px;
        }}
        .timestamp {{
            color: #999;
            font-size: 14px;
            margin-top: 10px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <div class="timestamp">Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}</div>
        
        <div class="summary">
            <h2>Executive Summary</h2>
            <div class="summary-item">
                <strong>Status:</strong> 
                <span class="status">{results.summary.get('status', 'unknown').replace('_', ' ').title()}</span>
            </div>
            <div class="summary-item">
                <strong>Total Insights:</strong> {results.summary.get('total_insights', 0)}
            </div>
            <div class="summary-item">
                <strong>Critical:</strong> {results.summary.get('critical_count', 0)}
            </div>
            <div class="summary-item">
                <strong>High Priority:</strong> {results.summary.get('high_count', 0)}
            </div>
            <p><strong>Next Action:</strong> {results.summary.get('next_action', 'N/A')}</p>
        </div>

        <h2>Key Metrics</h2>
        <div class="metrics">
"""

        for key, value in results.metrics.items():
            formatted_key = key.replace('_', ' ').title()
            formatted_value = f"{value:.2f}" if isinstance(value, float) else str(value)
            html += f"""
            <div class="metric">
                <div class="metric-value">{formatted_value}</div>
                <div class="metric-label">{formatted_key}</div>
            </div>
"""

        html += """
        </div>
"""

        if critical:
            html += """
        <h2>🔴 Critical Issues</h2>
"""
            for insight in critical:
                html += f"""
        <div class="insight critical">
            <h3>{insight.title}</h3>
            <p>{insight.description}</p>
            <div class="action"><strong>Action Required:</strong> {insight.action}</div>
        </div>
"""

        if high:
            html += """
        <h2>🟠 High Priority Items</h2>
"""
            for insight in high:
                html += f"""
        <div class="insight high">
            <h3>{insight.title}</h3>
            <p>{insight.description}</p>
            <div class="action"><strong>Recommended Action:</strong> {insight.action}</div>
        </div>
"""

        if results.recommendations:
            html += """
        <h2>Top Recommendations</h2>
        <div class="recommendations">
            <ol>
"""
            for rec in results.recommendations:
                html += f"                <li>{rec}</li>\n"

            html += """
            </ol>
        </div>
"""

        html += """
        <div class="timestamp" style="margin-top: 40px; text-align: center; border-top: 1px solid #ddd; padding-top: 20px;">
            Generated by SecBrain Insights
        </div>
    </div>
</body>
</html>
"""
        return html

    def generate_json(self, results: AnalysisResults) -> str:
        """
        Generate JSON report.

        Args:
            results: Analysis results

        Returns:
            JSON formatted report
        """
        data = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "summary": results.summary,
            "metrics": results.metrics,
            "insights": [
                {
                    "category": i.category,
                    "priority": i.priority,
                    "title": i.title,
                    "description": i.description,
                    "action": i.action,
                    "context": i.context,
                    "timestamp": i.timestamp,
                }
                for i in results.insights
            ],
            "recommendations": results.recommendations,
        }
        return json.dumps(data, indent=2)

    def generate_csv(self, results: AnalysisResults) -> str:
        """
        Generate CSV report of insights.

        Args:
            results: Analysis results

        Returns:
            CSV formatted report
        """
        output = StringIO()
        writer = csv.writer(output)

        # Header
        writer.writerow(["Category", "Priority", "Title", "Description", "Action", "Timestamp"])

        # Data
        for insight in results.insights:
            writer.writerow([
                insight.category,
                insight.priority,
                insight.title,
                insight.description,
                insight.action,
                insight.timestamp,
            ])

        return output.getvalue()

    def save_report(
        self,
        results: AnalysisResults,
        format: str = "markdown",
        filename: str | None = None,
    ) -> Path:
        """
        Save report to file.

        Args:
            results: Analysis results
            format: Output format (markdown, html, json, csv)
            filename: Optional filename (auto-generated if not provided)

        Returns:
            Path to saved file
        """
        if filename is None:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            ext = {"markdown": "md", "html": "html", "json": "json", "csv": "csv"}[format]
            filename = f"insights_report_{timestamp}.{ext}"

        filepath = self.output_dir / filename

        if format == "markdown":
            content = self.generate_markdown(results)
        elif format == "html":
            content = self.generate_html(results)
        elif format == "json":
            content = self.generate_json(results)
        elif format == "csv":
            content = self.generate_csv(results)
        else:
            msg = f"Unsupported format: {format}"
            raise ValueError(msg)

        filepath.write_text(content)
        return filepath

    def save_all_formats(self, results: AnalysisResults, base_filename: str = "insights_report") -> dict[str, Path]:
        """
        Save report in all formats.

        Args:
            results: Analysis results
            base_filename: Base filename (without extension)

        Returns:
            Dictionary mapping format to filepath
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        base = f"{base_filename}_{timestamp}"

        return {
            "markdown": self.save_report(results, "markdown", f"{base}.md"),
            "html": self.save_report(results, "html", f"{base}.html"),
            "json": self.save_report(results, "json", f"{base}.json"),
            "csv": self.save_report(results, "csv", f"{base}.csv"),
        }
