#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by Immunefi Instascope

set -e

echo "Building 39 contracts individually..."
echo ""

echo "Building Bank (contract_Bank_65fb)"
FOUNDRY_PROFILE=contract_Bank_65fb forge build || {
  echo "❌ Failed to build Bank"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Bank_65fb forge build"
}
echo "✅ Built Bank"
echo ""

echo "Building ProxyV5 (contract_ProxyV5_2111)"
FOUNDRY_PROFILE=contract_ProxyV5_2111 forge build || {
  echo "❌ Failed to build ProxyV5"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ProxyV5_2111 forge build"
}
echo "✅ Built ProxyV5"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_46d5)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_46d5 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_46d5 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building LightRelay (contract_LightRelay_836c)"
FOUNDRY_PROFILE=contract_LightRelay_836c forge build || {
  echo "❌ Failed to build LightRelay"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_LightRelay_836c forge build"
}
echo "✅ Built LightRelay"
echo ""

echo "Building TokenholderGovernor (contract_TokenholderGovernor_d101)"
FOUNDRY_PROFILE=contract_TokenholderGovernor_d101 forge build || {
  echo "❌ Failed to build TokenholderGovernor"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TokenholderGovernor_d101 forge build"
}
echo "✅ Built TokenholderGovernor"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_5e48)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_5e48 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_5e48 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_c903)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_c903 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_c903 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building MaintainerProxy (contract_MaintainerProxy_cf29)"
FOUNDRY_PROFILE=contract_MaintainerProxy_cf29 forge build || {
  echo "❌ Failed to build MaintainerProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_MaintainerProxy_cf29 forge build"
}
echo "✅ Built MaintainerProxy"
echo ""

echo "Building DonationVault (contract_DonationVault_a544)"
FOUNDRY_PROFILE=contract_DonationVault_a544 forge build || {
  echo "❌ Failed to build DonationVault"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_DonationVault_a544 forge build"
}
echo "✅ Built DonationVault"
echo ""

echo "Building WalletRegistry (contract_WalletRegistry_fbae)"
FOUNDRY_PROFILE=contract_WalletRegistry_fbae forge build || {
  echo "❌ Failed to build WalletRegistry"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_WalletRegistry_fbae forge build"
}
echo "✅ Built WalletRegistry"
echo ""

echo "Building EcdsaDkgValidator (contract_EcdsaDkgValidator_0125)"
FOUNDRY_PROFILE=contract_EcdsaDkgValidator_0125 forge build || {
  echo "❌ Failed to build EcdsaDkgValidator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EcdsaDkgValidator_0125 forge build"
}
echo "✅ Built EcdsaDkgValidator"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_b810)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_b810 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_b810 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building TBTC (contract_TBTC_1808)"
FOUNDRY_PROFILE=contract_TBTC_1808 forge build || {
  echo "❌ Failed to build TBTC"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TBTC_1808 forge build"
}
echo "✅ Built TBTC"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_75a6)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_75a6 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_75a6 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building CumulativeMerkleDrop (contract_CumulativeMerkleDrop_ea7c)"
FOUNDRY_PROFILE=contract_CumulativeMerkleDrop_ea7c forge build || {
  echo "❌ Failed to build CumulativeMerkleDrop"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_CumulativeMerkleDrop_ea7c forge build"
}
echo "✅ Built CumulativeMerkleDrop"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_5d4d)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_5d4d forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_5d4d forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building WalletRegistryGovernance (contract_WalletRegistryGovernance_6aed)"
FOUNDRY_PROFILE=contract_WalletRegistryGovernance_6aed forge build || {
  echo "❌ Failed to build WalletRegistryGovernance"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_WalletRegistryGovernance_6aed forge build"
}
echo "✅ Built WalletRegistryGovernance"
echo ""

echo "Building T (contract_T_cdf7)"
FOUNDRY_PROFILE=contract_T_cdf7 forge build || {
  echo "❌ Failed to build T"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_T_cdf7 forge build"
}
echo "✅ Built T"
echo ""

echo "Building TBTCVault (contract_TBTCVault_9c07)"
FOUNDRY_PROFILE=contract_TBTCVault_9c07 forge build || {
  echo "❌ Failed to build TBTCVault"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TBTCVault_9c07 forge build"
}
echo "✅ Built TBTCVault"
echo ""

echo "Building ReimbursementPool (contract_ReimbursementPool_8adf)"
FOUNDRY_PROFILE=contract_ReimbursementPool_8adf forge build || {
  echo "❌ Failed to build ReimbursementPool"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ReimbursementPool_8adf forge build"
}
echo "✅ Built ReimbursementPool"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_0184)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_0184 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_0184 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_b8df)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_b8df forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_b8df forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building WalletProposalValidator (contract_WalletProposalValidator_3001)"
FOUNDRY_PROFILE=contract_WalletProposalValidator_3001 forge build || {
  echo "❌ Failed to build WalletProposalValidator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_WalletProposalValidator_3001 forge build"
}
echo "✅ Built WalletProposalValidator"
echo ""

echo "Building Bridge (contract_Bridge_8d01)"
FOUNDRY_PROFILE=contract_Bridge_8d01 forge build || {
  echo "❌ Failed to build Bridge"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Bridge_8d01 forge build"
}
echo "✅ Built Bridge"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_01b6)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_01b6 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_01b6 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building SortitionPool (contract_SortitionPool_c273)"
FOUNDRY_PROFILE=contract_SortitionPool_c273 forge build || {
  echo "❌ Failed to build SortitionPool"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SortitionPool_c273 forge build"
}
echo "✅ Built SortitionPool"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_03e3)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_03e3 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_03e3 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building BridgeGovernance (contract_BridgeGovernance_a94d)"
FOUNDRY_PROFILE=contract_BridgeGovernance_a94d forge build || {
  echo "❌ Failed to build BridgeGovernance"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_BridgeGovernance_a94d forge build"
}
echo "✅ Built BridgeGovernance"
echo ""

echo "Building StarknetTokenBridge (contract_StarknetTokenBridge_f39d)"
FOUNDRY_PROFILE=contract_StarknetTokenBridge_f39d forge build || {
  echo "❌ Failed to build StarknetTokenBridge"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StarknetTokenBridge_f39d forge build"
}
echo "✅ Built StarknetTokenBridge"
echo ""

echo "Building WalletRegistry (contract_WalletRegistry_08d7)"
FOUNDRY_PROFILE=contract_WalletRegistry_08d7 forge build || {
  echo "❌ Failed to build WalletRegistry"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_WalletRegistry_08d7 forge build"
}
echo "✅ Built WalletRegistry"
echo ""

echo "Building Bridge (contract_Bridge_8ce2)"
FOUNDRY_PROFILE=contract_Bridge_8ce2 forge build || {
  echo "❌ Failed to build Bridge"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Bridge_8ce2 forge build"
}
echo "✅ Built Bridge"
echo ""

echo "Building StarkNetBitcoinDepositor (contract_StarkNetBitcoinDepositor_d358)"
FOUNDRY_PROFILE=contract_StarkNetBitcoinDepositor_d358 forge build || {
  echo "❌ Failed to build StarkNetBitcoinDepositor"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StarkNetBitcoinDepositor_d358 forge build"
}
echo "✅ Built StarkNetBitcoinDepositor"
echo ""

echo "Building BTCDepositorWormhole (contract_BTCDepositorWormhole_9a52)"
FOUNDRY_PROFILE=contract_BTCDepositorWormhole_9a52 forge build || {
  echo "❌ Failed to build BTCDepositorWormhole"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_BTCDepositorWormhole_9a52 forge build"
}
echo "✅ Built BTCDepositorWormhole"
echo ""

echo "Building L1BitcoinDepositor (contract_L1BitcoinDepositor_3ffe)"
FOUNDRY_PROFILE=contract_L1BitcoinDepositor_3ffe forge build || {
  echo "❌ Failed to build L1BitcoinDepositor"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_L1BitcoinDepositor_3ffe forge build"
}
echo "✅ Built L1BitcoinDepositor"
echo ""

echo "Building L1BTCRedeemerWormhole (contract_L1BTCRedeemerWormhole_14d9)"
FOUNDRY_PROFILE=contract_L1BTCRedeemerWormhole_14d9 forge build || {
  echo "❌ Failed to build L1BTCRedeemerWormhole"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_L1BTCRedeemerWormhole_14d9 forge build"
}
echo "✅ Built L1BTCRedeemerWormhole"
echo ""

echo "Building RebateStaking (contract_RebateStaking_e490)"
FOUNDRY_PROFILE=contract_RebateStaking_e490 forge build || {
  echo "❌ Failed to build RebateStaking"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_RebateStaking_e490 forge build"
}
echo "✅ Built RebateStaking"
echo ""

echo "Building RedemptionWatchtower (contract_RedemptionWatchtower_bfd0)"
FOUNDRY_PROFILE=contract_RedemptionWatchtower_bfd0 forge build || {
  echo "❌ Failed to build RedemptionWatchtower"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_RedemptionWatchtower_bfd0 forge build"
}
echo "✅ Built RedemptionWatchtower"
echo ""

echo "Building TokenStaking (contract_TokenStaking_f5a2)"
FOUNDRY_PROFILE=contract_TokenStaking_f5a2 forge build || {
  echo "❌ Failed to build TokenStaking"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TokenStaking_f5a2 forge build"
}
echo "✅ Built TokenStaking"
echo ""

echo "Building LockReleaseTokenPoolUpgradeable (contract_LockReleaseTokenPoolUpgradeable_7ff0)"
FOUNDRY_PROFILE=contract_LockReleaseTokenPoolUpgradeable_7ff0 forge build || {
  echo "❌ Failed to build LockReleaseTokenPoolUpgradeable"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_LockReleaseTokenPoolUpgradeable_7ff0 forge build"
}
echo "✅ Built LockReleaseTokenPoolUpgradeable"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
