#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by Immunefi Instascope

set -e

echo "Building 25 contracts individually..."
echo ""

echo "Building Proxy (contract_Proxy_85b7)"
FOUNDRY_PROFILE=contract_Proxy_85b7 forge build || {
  echo "❌ Failed to build Proxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Proxy_85b7 forge build"
}
echo "✅ Built Proxy"
echo ""

echo "Building ConvexEthMetaStrategyProxy (contract_ConvexEthMetaStrategyProxy_1827)"
FOUNDRY_PROFILE=contract_ConvexEthMetaStrategyProxy_1827 forge build || {
  echo "❌ Failed to build ConvexEthMetaStrategyProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ConvexEthMetaStrategyProxy_1827 forge build"
}
echo "✅ Built ConvexEthMetaStrategyProxy"
echo ""

echo "Building VaultProxy (contract_VaultProxy_e75d)"
FOUNDRY_PROFILE=contract_VaultProxy_e75d forge build || {
  echo "❌ Failed to build VaultProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_VaultProxy_e75d forge build"
}
echo "✅ Built VaultProxy"
echo ""

echo "Building OETHCurveAMOProxy (contract_OETHCurveAMOProxy_af04)"
FOUNDRY_PROFILE=contract_OETHCurveAMOProxy_af04 forge build || {
  echo "❌ Failed to build OETHCurveAMOProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_OETHCurveAMOProxy_af04 forge build"
}
echo "✅ Built OETHCurveAMOProxy"
echo ""

echo "Building FixedRateRewardsSourceProxy (contract_FixedRateRewardsSourceProxy_7609)"
FOUNDRY_PROFILE=contract_FixedRateRewardsSourceProxy_7609 forge build || {
  echo "❌ Failed to build FixedRateRewardsSourceProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_FixedRateRewardsSourceProxy_7609 forge build"
}
echo "✅ Built FixedRateRewardsSourceProxy"
echo ""

echo "Building ExponentialStakingProxy (contract_ExponentialStakingProxy_6389)"
FOUNDRY_PROFILE=contract_ExponentialStakingProxy_6389 forge build || {
  echo "❌ Failed to build ExponentialStakingProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ExponentialStakingProxy_6389 forge build"
}
echo "✅ Built ExponentialStakingProxy"
echo ""

echo "Building InitializeGovernedUpgradeabilityProxy (contract_InitializeGovernedUpgradeabilityProxy_5018)"
FOUNDRY_PROFILE=contract_InitializeGovernedUpgradeabilityProxy_5018 forge build || {
  echo "❌ Failed to build InitializeGovernedUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_InitializeGovernedUpgradeabilityProxy_5018 forge build"
}
echo "✅ Built InitializeGovernedUpgradeabilityProxy"
echo ""

echo "Building WOETHProxy (contract_WOETHProxy_dcee)"
FOUNDRY_PROFILE=contract_WOETHProxy_dcee forge build || {
  echo "❌ Failed to build WOETHProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_WOETHProxy_dcee forge build"
}
echo "✅ Built WOETHProxy"
echo ""

echo "Building Governance (contract_Governance_1d3f)"
FOUNDRY_PROFILE=contract_Governance_1d3f forge build || {
  echo "❌ Failed to build Governance"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Governance_1d3f forge build"
}
echo "✅ Built Governance"
echo ""

echo "Building CompoundingStakingStrategyView (contract_CompoundingStakingStrategyView_edf4)"
FOUNDRY_PROFILE=contract_CompoundingStakingStrategyView_edf4 forge build || {
  echo "❌ Failed to build CompoundingStakingStrategyView"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_CompoundingStakingStrategyView_edf4 forge build"
}
echo "✅ Built CompoundingStakingStrategyView"
echo ""

echo "Building BeaconProofs (contract_BeaconProofs_c444)"
FOUNDRY_PROFILE=contract_BeaconProofs_c444 forge build || {
  echo "❌ Failed to build BeaconProofs"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_BeaconProofs_c444 forge build"
}
echo "✅ Built BeaconProofs"
echo ""

echo "Building MigratorProxy (contract_MigratorProxy_95c3)"
FOUNDRY_PROFILE=contract_MigratorProxy_95c3 forge build || {
  echo "❌ Failed to build MigratorProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_MigratorProxy_95c3 forge build"
}
echo "✅ Built MigratorProxy"
echo ""

echo "Building OETHVaultProxy (contract_OETHVaultProxy_3925)"
FOUNDRY_PROFILE=contract_OETHVaultProxy_3925 forge build || {
  echo "❌ Failed to build OETHVaultProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_OETHVaultProxy_3925 forge build"
}
echo "✅ Built OETHVaultProxy"
echo ""

echo "Building InitializeGovernedUpgradeabilityProxy (contract_InitializeGovernedUpgradeabilityProxy_2a8e)"
FOUNDRY_PROFILE=contract_InitializeGovernedUpgradeabilityProxy_2a8e forge build || {
  echo "❌ Failed to build InitializeGovernedUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_InitializeGovernedUpgradeabilityProxy_2a8e forge build"
}
echo "✅ Built InitializeGovernedUpgradeabilityProxy"
echo ""

echo "Building LidoARM (contract_LidoARM_c029)"
FOUNDRY_PROFILE=contract_LidoARM_c029 forge build || {
  echo "❌ Failed to build LidoARM"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_LidoARM_c029 forge build"
}
echo "✅ Built LidoARM"
echo ""

echo "Building ConvexEthMetaStrategy (contract_ConvexEthMetaStrategy_5c93)"
FOUNDRY_PROFILE=contract_ConvexEthMetaStrategy_5c93 forge build || {
  echo "❌ Failed to build ConvexEthMetaStrategy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ConvexEthMetaStrategy_5c93 forge build"
}
echo "✅ Built ConvexEthMetaStrategy"
echo ""

echo "Building VaultCore (contract_VaultCore_6b89)"
FOUNDRY_PROFILE=contract_VaultCore_6b89 forge build || {
  echo "❌ Failed to build VaultCore"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_VaultCore_6b89 forge build"
}
echo "✅ Built VaultCore"
echo ""

echo "Building CompoundingStakingSSVStrategy (contract_CompoundingStakingSSVStrategy_452b)"
FOUNDRY_PROFILE=contract_CompoundingStakingSSVStrategy_452b forge build || {
  echo "❌ Failed to build CompoundingStakingSSVStrategy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_CompoundingStakingSSVStrategy_452b forge build"
}
echo "✅ Built CompoundingStakingSSVStrategy"
echo ""

echo "Building FixedRateRewardsSource (contract_FixedRateRewardsSource_1689)"
FOUNDRY_PROFILE=contract_FixedRateRewardsSource_1689 forge build || {
  echo "❌ Failed to build FixedRateRewardsSource"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_FixedRateRewardsSource_1689 forge build"
}
echo "✅ Built FixedRateRewardsSource"
echo ""

echo "Building ExponentialStaking (contract_ExponentialStaking_9771)"
FOUNDRY_PROFILE=contract_ExponentialStaking_9771 forge build || {
  echo "❌ Failed to build ExponentialStaking"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ExponentialStaking_9771 forge build"
}
echo "✅ Built ExponentialStaking"
echo ""

echo "Building SingleAssetStaking (contract_SingleAssetStaking_3675)"
FOUNDRY_PROFILE=contract_SingleAssetStaking_3675 forge build || {
  echo "❌ Failed to build SingleAssetStaking"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SingleAssetStaking_3675 forge build"
}
echo "✅ Built SingleAssetStaking"
echo ""

echo "Building WOETH (contract_WOETH_3887)"
FOUNDRY_PROFILE=contract_WOETH_3887 forge build || {
  echo "❌ Failed to build WOETH"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_WOETH_3887 forge build"
}
echo "✅ Built WOETH"
echo ""

echo "Building Migrator (contract_Migrator_936b)"
FOUNDRY_PROFILE=contract_Migrator_936b forge build || {
  echo "❌ Failed to build Migrator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Migrator_936b forge build"
}
echo "✅ Built Migrator"
echo ""

echo "Building OETHVaultCore (contract_OETHVaultCore_2243)"
FOUNDRY_PROFILE=contract_OETHVaultCore_2243 forge build || {
  echo "❌ Failed to build OETHVaultCore"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_OETHVaultCore_2243 forge build"
}
echo "✅ Built OETHVaultCore"
echo ""

echo "Building OUSD (contract_OUSD_a7b7)"
FOUNDRY_PROFILE=contract_OUSD_a7b7 forge build || {
  echo "❌ Failed to build OUSD"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_OUSD_a7b7 forge build"
}
echo "✅ Built OUSD"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
